# Версия docker-compose
version: '3.3'

# Список наших сервисов (контейнеров)
services:
  web:
    image: "ilbru/openserver:latest"
    ports:
      - "8080:80"
    volumes:
      - ${WORK_PATH}/work:/srv/www/htdocs/
      - ${WORK_PATH}/.config/context.xml:/var/lib/wwwrun/.config/context.xml
      - ${WORK_PATH}/apps:/var/apps
      - ${WORK_PATH}/log:/var/log/webapp
      - ./logs/apache2:/var/log/apache2
      - ./logs/php:/var/log/php
      - ./code/web.sh:/var/code/web.sh
    entrypoint: /var/code/web.sh
    links:
      - db
  db:
    image: "mariadb"
    command: mysqld --sql_mode=""
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: openserver
  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
